<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Windows.Forms.DataVisualization" Version="1.0.0-prerelease.20110.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="QRCoder" Version="1.4.3" />
  </ItemGroup>

</Project>